@host = http://localhost:5258

# @name writerLogin
POST {{host}}/api/auth/token
Content-Type: application/json

{
  "username": "writer",
  "password": "writer123"
}

###

# @name readerLogin
POST {{host}}/api/auth/token
Content-Type: application/json

{
  "username": "reader",
  "password": "reader123"
}

###

# @name ownerLogin
POST {{host}}/api/auth/token
Content-Type: application/json

{
  "username": "owner",
  "password": "owner123"
}

###

POST {{host}}/api/products
Authorization: Bearer {{ownerLogin.response.body.accessToken}}
Content-Type: application/json

{
  "name": "Schreibtisch",
  "description": "Höhenverstellbar",
  "price": 499.99
}

###

POST {{host}}/api/products
Authorization: Bearer {{ownerLogin.response.body.accessToken}}
Content-Type: application/json

{
  "name": "Schreibtisch",
  "description": "Fixiert",
  "price": 399.99
}

### 

POST {{host}}/api/products/reset
Authorization: Bearer {{ownerLogin.response.body.accessToken}}

###

GET {{host}}/api/products
Authorization: Bearer {{ownerLogin.response.body.accessToken}}
Accept: application/json

###

GET {{host}}/api/products/4
Authorization: Bearer {{ownerLogin.response.body.accessToken}}
Accept: application/json

###

GET {{host}}/api/products/1
Accept: application/json

###

PUT {{host}}/api/products/1
Content-Type: application/json  

{
  "name": "Schreibtisch",
  "description": "Höhenverstellbar",
  "price": 499.99
}

###

DELETE {{host}}/api/products/2

###